# This is a TOML document
Nants_telescope = 20
Nants_data = 20
Ntimes = 0 # initially
Nfreqs = 192
Npols = 2
Nspws = 1
Nbls = 0 # auto
Nblts = 0 # initially
latitude = 121.28
longitude = 40.49
altitude = 986.0
telescope_name = "bogus"
instrument = uvh5_header->telescope_name
object_name = "zenith"
history = "None"
phase_type = "drift"
flex_spw = false

antenna_numbers = [] # auto
antenna_names = [
	"1", "2"
]
antenna_positions = [

]
antenna_positions = [

]
antenna_positions = [

]